version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: node:8.8.1
    steps:
      - checkout
      - run: npm install
      - run: ./node_modules/.bin/bower install --allow-root
      - run: make test
